-- Create contacts table for the contact form
CREATE TABLE IF NOT EXISTS contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  discord TEXT,
  message TEXT NOT NULL
);

-- Create subscribers table for the newsletter
CREATE TABLE IF NOT EXISTS subscribers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  email TEXT UNIQUE NOT NULL
);

-- Set up Row Level Security (RLS)
-- Allow anyone to insert (so people can contact you / subscribe)
-- But don't allow anonymous users to read your data

ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow anonymous inserts to contacts" ON contacts FOR INSERT WITH CHECK (true);

ALTER TABLE subscribers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow anonymous inserts to subscribers" ON subscribers FOR INSERT WITH CHECK (true);
